language: ruby
rvm:
 - jruby

before_install:
- yes | gem update --system --force
- gem install bundler

jobs:
  include:
    - stage: Test, Unit, Lint, Coverage
      script:
        - test/run_all_tests.sh
