env:
  global:
    - JRUBY_OPTS="--debug"
language: ruby
rvm:
  - jruby-9.2.13.0
os: linux
dist: xenial
script:
  - echo "TESTS BY LIBRARY"
  - test/run_by_library_tests.sh
  - echo "TESTS BY PRODUCER ROLE"
  - test/run_producer_role_tests.sh
  - test/run_all_tests.sh
  - bundle exec rubocop
  - bundle exec reek .
