language: ruby
rvm:
 - jruby

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

jobs:
  include:
    - stage: Test, Unit, Lint, Coverage
      script:
        - test/run_all_tests.sh
